### ISSUE TITLE
"'NoneType' Object is not iterable" when accessing contacts

### ISSUE THREAD

**Issue by DerGenaue** [OllieTerrance/SkPy#90] opened 2018-06-24 00:08 UTC
There currently seems to be a weird issue whenever you try to access contacts in specific ways:

Try to access a contact using the array-form:

```python
>>> sk.contacts['test']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "\Python36\lib\site-packages\skpy\user.py", line 348, in __getitem__
    return super(SkypeContacts, self).__getitem__(key)
  File "\Python36\lib\site-packages\skpy\core.py", line 137, in __getitem__
    self.sync()
  File "\Python36\lib\site-packages\skpy\user.py", line 378, in sync
    self.groups[json.get("name", json.get("id"))] = SkypeContactGroup.fromRaw(self.skype, json)
  File "\Python36\lib\site-packages\skpy\core.py", line 61, in fromRaw
    return cls(skype, raw, **cls.rawToFields(raw))
  File "\Python36\lib\site-packages\skpy\user.py", line 505, in rawToFields
    "userIds": [SkypeUtils.noPrefix(id) for id in raw.get("contacts")]}
TypeError: 'NoneType' object is not iterable
>>>
```

The same triggers if you receive a message from your self in the event loop and try to access the user-id:

```python
>>> msg.user.id
Traceback (most recent call last):
  File "/python3.4/dist-packages/SkPy-0.0.0-py3.4.egg/skpy/util.py", line 142, in userObj
    return self.skype.contacts[getattr(self, field)]
  File "/python3.4/dist-packages/SkPy-0.0.0-py3.4.egg/skpy/user.py", line 353, in __getitem__
    return super(SkypeContacts, self).__getitem__(key)
  File "/python3.4/dist-packages/SkPy-0.0.0-py3.4.egg/skpy/core.py", line 137, in __getitem__
    self.sync()
  File "/python3.4/dist-packages/SkPy-0.0.0-py3.4.egg/skpy/user.py", line 383, in sync
    self.groups[json.get("name", json.get("id"))] = SkypeContactGroup.fromRaw(self.skype, json)
  File "/python3.4/dist-packages/SkPy-0.0.0-py3.4.egg/skpy/core.py", line 61, in fromRaw
    return cls(skype, raw, **cls.rawToFields(raw))
  File "/python3.4/dist-packages/SkPy-0.0.0-py3.4.egg/skpy/user.py", line 509, in rawToFields
    "userIds": [SkypeUtils.noPrefix(id) for id in raw.get("contacts")]}
TypeError: 'NoneType' object is not iterable
```

I'm assuming this is due to your current rework of the contacts endpoint?

**Comment by OllieTerrance** [comment] 2018-06-24 08:41
There isn't a current rework, besides #85 to change the point which is done fixed on master.

You also didn't include the network requests as noted in the issue template, so I'm unable to proceed -- I don't know what response you got from Skype, and I can't reproduce it locally.

```python
>>> sk.contacts["test"]
SkypeUser(id='test', name=Name(), location=Location(),
          avatar='https://avatar.skype.com/v1/avatars/test/public')
```

**Comment by DerGenaue** [comment] 2018-06-24 13:14
O.o ... I had the same issue on two different systems so I thought reproduction wouldn't be an issue at all...
let me do some more debugging...

**Comment by DerGenaue** [comment] 2018-06-24 14:05
The Endpoint seems to return the data completely fine:
```
<= [24/06 15:50:56] GET https://contacts.skype.com/contacts/v2/users/<username>
{'params': {'delta': '', 'reason': 'default'}}
=> [24/06 15:50:56] 200
{'Cache-Control': 'no-cache, no-store, must-revalidate, private, max-age=0',
 'Content-Encoding': 'gzip',
 'Content-Type': 'application/json; charset=utf-8',
 'Date': 'Sun, 24 Jun 2018 13:50:55 GMT',
 'ETag': '"g|0000|0000000000000000291|2018-06-24T13:50:55.7996053Z"',
 'Server': 'Microsoft-HTTPAPI/2.0',
 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
 'Transfer-Encoding': 'chunked',
 'Vary': 'Accept-Encoding',
 'X-Correlation-Id': '<id>',
 'X-Role-Instance': '<id>/45',
 'X-Session': '<id>'}
{'blocklist': [{'mri': '8:<id>'},
               {'mri': '8:<id>'}],
 'contacts': [{'auth_certificate': '<blob>',
               'authorized': True,
               'blocked': False,
               'creation_time': '<timestamp>',
               'display_name': '<name>',
               'display_name_source': 'profile',
               'explicit': True,
               'mri': '8:<id>',
               'person_id': '8:<id>',
               'profile': {'avatar_url': '<link>',
                           'name': {'first': '<name>',
                                    'nickname': '<id>',
                                    'surname': '<name>'}}},
              {'auth_certificate': '<blob>',
               'authorized': True,
               'blocked': False,
               'creation_time': '<timestamp>',
               'display_name': '<name>',
               'display_name_source': 'profile',
               'explicit': True,
               'mri': '8:<id>',
               'person_id': '8:<id>',
               'profile': {'avatar_url': '<url>',
                           'birthday': '<date>',
                           'gender': '<g>',
                           'language': '<ln>',
                           'locations': [{'country': '<c>', 'type': 'home'}],
                           'name': {'first': '<name>',
                                    'nickname': '<id>',
                                    'surname': '<name>'}}}],
 'groups': [{'contacts': ['8:<id>',
                          '8:<id>'],
             'id': '<id>',
             'name': '<name>'},
            {'id': '<id>',
             'is_favorite': True,
             'name': 'Favorites'},
            {'contacts': ['8:<id>',
                          '8:<id>'],
             'id': '<id>',
             'name': '<name>'}],
 'scope': 'full'}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "\Python36\lib\site-packages\skpy\user.py", line 348, in __getitem__
    return super(SkypeContacts, self).__getitem__(key)
  File "\Python36\lib\site-packages\skpy\core.py", line 137, in __getitem__
    self.sync()
  File "\Python36\lib\site-packages\skpy\user.py", line 378, in sync
    self.groups[json.get("name", json.get("id"))] = SkypeContactGroup.fromRaw(self.skype, json)
  File "\Python36\lib\site-packages\skpy\core.py", line 61, in fromRaw
    return cls(skype, raw, **cls.rawToFields(raw))
  File "\Python36\lib\site-packages\skpy\user.py", line 505, in rawToFields
    "userIds": [SkypeUtils.noPrefix(id) for id in raw.get("contacts")]}
TypeError: 'NoneType' object is not iterable

```

**Comment by DerGenaue** [comment] 2018-06-24 14:18
Found it:
In the groups-part of the response, the "Favourites"-Group has no contacts in it;
And the property is just left out completely...
Solution is to change line 505 of `user.py` to contain a default value: `raw.get("contacts", [])`

**Comment by OllieTerrance** [comment] 2018-06-24 14:58
Hopefully that should do it.  👍

**Closed** 2018-06-24 14:57 UTC
Labels: bug
