### ISSUE TITLE
KeyError: 'missed' [bug]

### ISSUE THREAD

**Issue by olegspk** [OllieTerrance/SkPy#88] opened 2018-06-14 12:54 UTC
I have a permanent error in the skpy, after start process check messages with method getMsgs(), if chat have a missed call from user skype.

How can it be fixed?
### Account type
Live

### Conversation details
<class 'skpy.msg.SkypeCallMsg'>
fields: 
```
{
'chatId': '8:user', 
'clientId': '893623686024XXXXX08', 
'content': '<partlist type="missed" alt="" callId="2dd6272a-22c9-XXXc-86ef-beXXXda8fbXX"><part identity="user"><name>User name</name></part><part identity="8:live:user_8"><name>User 2018</name></part></partlist>', 
'id': '152896XXXXX01', 
'time': datetime.datetime(2018, 6, 14, 9, 35, 39, 8000), 
'type': 'Event/Call', 
'userId': 'user'
}
```

listTag: 
`<partlist alt="" callid="2dd6272a-22c9-XXXc-86ef-beXXXda8fbXX" type="missed"><part identity="user"><name>User name</name></part><part identity="8:live:user_8"><name>User 2018</name></part></partlist>`

### Steps to reproduce
SkPy can't process event: missed call from user in the chat.

### Result or traceback
KeyError: 'missed'
    for skype_msg in ch.getMsgs():
  File "skpy/chat.py", line 48, in getMsgs
    return [SkypeMsg.fromRaw(self.skype, json) for json in resp.get("messages", [])]
  File "skpy/chat.py", line 48, in <listcomp>
    return [SkypeMsg.fromRaw(self.skype, json) for json in resp.get("messages", [])]
  File "skpy/msg.py", line 251, in fromRaw
    return msgCls(skype, raw, **msgCls.rawToFields(raw))
  File "skpy/msg.py", line 652, in rawToFields
    fields.update({"state": {"started": cls.State.Started, "ended": cls.State.Ended}[listTag.get("type")],

Error in skpy (skpy/msg.py in rawToFields at line 652):
```
    @classmethod
    def rawToFields(cls, raw={}):
        fields = super(SkypeCallMsg, cls).rawToFields(raw)
        listTag = BeautifulSoup(raw.get("content"), "html.parser").find("partlist")
        fields.update({"state": {"started": cls.State.Started, "ended": cls.State.Ended}[listTag.get("type")],
```

**Comment by OllieTerrance** [comment] 2018-06-14 13:10
Duplicate of #83, though that ought to go out in a release by now...

**Closed by OllieTerrance** 2018-06-14 13:10 UTC
