### ISSUE TITLE
404 error while trying to login via Live (Microsoft) account.

### ISSUE THREAD

**Issue by sathishbob** [OllieTerrance/SkPy#54] opened 2017-04-10 09:35 UTC
HI,

When i try to login using Skype account, its working fine

But when i try to login using Live (Microsoft) account, its throwing 404 error

('404 response from PUT https://client-s.gateway.messenger.live.com/v1/users/ME/endpoints/5434e4d6-34f7-9d2c-783d-8dbc04cfe714/presenceDocs/messagingService', <Response [404]>)

### Steps to reproduce
Just trying to login

from skpy import Skype

from getpass import getpass

Skype("XXX@yyy.com", getpass())

### Result or traceback

Password: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/skpy/main.py", line 67, in __init__
    self.conn.readToken()
  File "/usr/local/lib/python3.6/site-packages/skpy/conn.py", line 284, in readToken
    raise SkypeAuthException("No token file specified")
skpy.core.SkypeAuthException: No token file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    Skype("sathish.babu@borngroup.com", getpass())
  File "/usr/local/lib/python3.6/site-packages/skpy/main.py", line 69, in __init__
    self.conn.getSkypeToken()
  File "/usr/local/lib/python3.6/site-packages/skpy/conn.py", line 262, in getSkypeToken
    self.liveLogin(user, pwd)
  File "/usr/local/lib/python3.6/site-packages/skpy/conn.py", line 361, in liveLogin
    self.getRegToken()
  File "/usr/local/lib/python3.6/site-packages/skpy/conn.py", line 421, in getRegToken
    endpoint.config()
  File "/usr/local/lib/python3.6/site-packages/skpy/conn.py", line 864, in config
    "version": "908/1.30.0.128"}})
  File "/usr/local/lib/python3.6/site-packages/skpy/conn.py", line 215, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
skpy.core.SkypeApiException: ('404 response from PUT https://client-s.gateway.messenger.live.com/v1/users/ME/endpoints/5434e4d6-34f7-9d2c-783d-8dbc04cfe714/presenceDocs/messagingService', <Response [404]>)

**Comment by OllieTerrance** [comment] 2017-04-10 09:55
Duplicate of #47 -- I have yet to see this on my end; it appears to be a temporary issue with Skype's servers.

If you can reliably reproduce this, please compare the failing request with the corresponding one made by [Skype for Web](https://web.skype.com) in dev tools, it might be doing something differently to handle this case.

**Comment by raghunathgit** [comment] 2017-04-10 11:38
HI,

I did a comparison,After the below post

<= [10/04 11:28:24] POST https://client-s.gateway.messenger.live.com/v1/users/ME/endpoints
{'json': {'endpointFeatures': 'Agent'}}

we are getting 200 for live account

=> [10/04 11:28:27] 200
[{'id': '12de317a-4c98-4825-97a0-fbc75c2dd2db',
  'isActive': False,
  'networks': [],
  'policies': {},
  'subscriptions': [{'channelType': 'HttpLongPoll',
                     'conversationType': 0,
                     'eventChannel': '0',
                     'eventServiceName': '',
                     'id': 0,
                     'interestedResources': ['/v1/threads/ALL',
                                             '/v1/users/ME/conversations/ALL/messages',
                                             '/v1/users/ME/conversations/ALL/properties',
                                             '/v1/users/ME/contacts/ALL'],
                     'packageSid': '',
                     'template': '',
                     'type': 'Subscription',
                     'xuid': ''}],
  'type': 'Endpoint'},
 {'id': '5434e4d6-34f7-9d2c-783d-8dbc04cfe714',
  'isActive': True,
  'networks': [],
  'policies': {},
  'subscriptions': [{'channelType': 'TcpSocket',
                     'conversationType': 0,
                     'eventChannel': '',
                     'eventServiceName': '',
                     'id': 0,
                     'interestedResources': ['/abch',
                                             '/v1/threads/ALL',
                                             '/v1/users/ME/conversations/ALL/messages',
                                             '/v1/users/ME/conversations/ALL/properties',
                                             '/v1/users/ME/contacts/ALL'],
                     'packageSid': '',
                     'template': '',
                     'type': 'Subscription',
                     'xuid': ''}],
  'type': 'Endpoint'}]

But for skype account we are getting 201

[10/04 11:47:44] 201

End point url for skpe account is different
= [10/04 11:47:44] PUT **https://co4-client-**s.gateway.messenger.live.com/v1/users/ME/endpoints/{575b348f-f468-40b8-87de-f100b649501b}/presenceDocs/messagingService
{'json': {'id': 'messagingService',
          'privateInfo': {'epname': 'skype'},
          'publicInfo': {'capabilities': '',
                         'nodeInfo': 'xx',
                         'skypeNameVersion': 'skype.com',
                         'type': 1,
                         'version': '908/1.30.0.128'},
          'selfLink': 'uri',
          'type': 'EndpointPresenceDoc'}}

for live account endpoint it is 
[10/04 11:28:27] PUT https://client-s.gateway.messenger.live.com/v1/users/ME/endpoints/12de317a-4c98-4825-97a0-fbc75c2dd2db/presenceDocs/messagingService
{'json': {'id': 'messagingService',
          'privateInfo': {'epname': 'skype'},
          'publicInfo': {'capabilities': '',
                         'nodeInfo': 'xx',
                         'skypeNameVersion': 'skype.com',
                         'type': 1,
                         'version': '908/1.30.0.128'},
          'selfLink': 'uri',
          'type': 'EndpointPresenceDoc'}}

and its returning 404

**Comment by OllieTerrance** [comment] 2017-04-10 12:01
Skype uses multiple "clouds", with different users directed to different host domains.  The Live account appears not to get redirected and uses the base domain (which afaict is a valid case).

> ...please compare the failing request with the corresponding one made by [Skype for Web](https://web.skype.com) in dev tools...

Does Skype for Web use the base domain too?

**Comment by AshotS** [comment] 2017-04-20 07:43
Hi.
I have the same problem.
> Does Skype for Web use the base domain too?
No. In my case Skype use db5-client-s.gateway.messenger.live.com If i change API_MSGSHOST to db5-client-s.gateway.messenger.live.com then everything works fine. Any ideas how to get the correct URL?

**Comment by OllieTerrance** [comment] 2017-04-20 12:01
Just tried it again with my test Live account:

```python
>>> sk = Skype("fred.adams@live.co.uk", getpass())
Password:
>>> sk
Skype(userId='live:fred_2')
>>> sk.conn.msgsHost
'https://db5-client-s.gateway.messenger.live.com/v1'
```

So it looks like alternate hosts are working in some cases.

@AshotS: Can you tell from Skype from Web, how it might be deciding to switch hostnames?  Take a look at the last request made to the base domain, it'll likely be reading something out of the Location header or JSON response.  The relevant SkPy code for detecting the hostname can be found [here](https://github.com/OllieTerrance/SkPy/blob/master/skpy/conn.py#L709-L737).

I'm wondering if there's an endpoint from a different domain, then you're supposed to follow that...

**Comment by AshotS** [comment] 2017-04-20 12:40
@OllieTerrance Your code works correctly. Now I tried to find a problem but everything works. It is very strange.

**Comment by OllieTerrance** [comment] 2017-04-20 13:14
That's what everyone's said, it always seems to be temporary...  😞

**Comment by AshotS** [comment] 2017-04-20 13:55
I think I found the problem. [https://ibb.co/jwVyWQ]() When I added to the headers "BehaviorOverride": "redirectAs404"  "Location" appeared in response. 
`{'Cache-Control': 'no-store, must-revalidate, no-cache',
 'Content-Length': '106',
 'Content-Type': 'application/json; charset=utf-8',
 'ContextId': 'tcid=3024622139195838359,server=CO2SCH020011330',
 'Date': 'Thu, 20 Apr 2017 13:46:14 GMT',
 'Location': 'https://db5-client-s.gateway.messenger.live.com/v1/users/ME/endpoints',
 'Pragma': 'no-cache',
 'Set-RegistrationToken': 'registrationToken=XBZMkYwYVc5dVVtVmhaRTl1YkhrPTs=; '
                          'expires=1492782373; '
                          'endpointId={6317ef51-1d84-413e-8185-9be34f0d3cae}'}
{'errorCode': 752,
 'message': "User is in a different cloud. See 'Location' header for users "
            'current cloud.'}
`

**Comment by OllieTerrance** [comment] 2017-04-20 17:53
I've added the `BehaviorOverride` header -- I've yet to come across this issue, and coupled with its temporary nature, it's a bit tricky to test!  Explicitly testing for the error code shouldn't be necessary as we're always checking the `Location` header?

**Comment by AshotS** [comment] 2017-04-20 19:15
> Explicitly testing for the error code shouldn't be necessary as we're always checking the Location header

Verification is needed in order to send a repeated request to the URL received from Location. At least in Web Skype is implemented in this way. If response return 404 client get URL from Location and post request again in new URL. Otherwise there is the exact same error.

**Comment by OllieTerrance** [comment] 2017-04-21 17:49
I'm inclined not to check for server error codes when, due to being a private, undocumented API, they're liable to change or mean different things.  But it should now be the case that if we get a different hostname back, we always re-request until it sticks.

**Comment by AshotS** [comment] 2017-04-21 19:14
Yes, this idea is much better. Thank you.

**Comment by OllieTerrance** [comment] 2017-04-21 19:56
Hopefully that'll cover it.  Still unsure why it only happens temporarily...

I'll get it pushed out on PyPI shortly as this has affected quite a few users now.  If we still get this cropping up, I'll reopen for further investigation.

**Closed by OllieTerrance** 2017-04-21 19:56 UTC
Labels: duplicate, question
