### ISSUE TITLE
"SkypeApiException: 404 response from PUT" on init

### ISSUE THREAD

**Issue by trikota** [OllieTerrance/SkPy#47] opened 2017-03-03 14:03 UTC
Hi! First of all, great project, thank you!
I have written a script that sends messages using SkPy. There are around 50 microsoft live accounts that work well and good. 
However, there is one account, insignificant in any way, that raises error on this line :
`sk = Skype(login, pass)`
Where login is "@hotmail.com" . (btw, this non-working one is @outlook.com) 
Full Traceback:
>   File "C:\Python27\Lib\site-packages\skpy\main.py", line 69, in __init__
    self.conn.getSkypeToken()
  File "C:\Python27\Lib\site-packages\skpy\conn.py", line 263, in getSkypeToken
    self.liveLogin(user, pwd)
  File "C:\Python27\Lib\site-packages\skpy\conn.py", line 362, in liveLogin
    self.getRegToken()
  File "C:\Python27\Lib\site-packages\skpy\conn.py", line 423, in getRegToken
    endpoint.config()
  File "C:\Python27\Lib\site-packages\skpy\conn.py", line 867, in config
    "version": "908/1.30.0.128"}})
  File "C:\Python27\Lib\site-packages\skpy\conn.py", line 216, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code,
 method, url), resp)
skpy.core.SkypeApiException: ('404 response from PUT https://client-s.gateway.me
ssenger.live.com/v1/users/ME/endpoints/bee77efb-7a06-692a-aafd-97a003fd126c/pres
enceDocs/messagingService', <Response [404]>)

Response body is
`{"errorCode":729,"message":"You must create an endpoint before performing this o
peration."}`

**Comment by OllieTerrance** [comment] 2017-03-03 17:55
Sounds like #42 again...  🙁

Please try the following:
* set `SKPY_DEBUG_HTTP=1` in your environment
* add a line to debug the response headers:
```diff
diff --git a/skpy/conn.py b/skpy/conn.py
index de1fcdd..58df16c 100644
--- a/skpy/conn.py
+++ b/skpy/conn.py
@@ -116,4 +116,5 @@ class SkypeConnection(SkypeObj):
         if os.getenv("SKPY_DEBUG_HTTP"):
             print("=> [{0}] {1}".format(datetime.now().strftime("%d/%m %H:%M:%S"), resp.status_code))
+            print(pformat(dict(resp.headers)))
             try:
                 print(pformat(resp.json()))
```
* uncomment those endpoint lines and retry
* paste the output for the failing step (PUT messagingService) and the previous one (POST endpoints)

I suspect you're seeing something similar -- 200 response on the POST but no viable endpoint.

**Comment by trikota** [comment] 2017-03-03 20:37
Thanks for answer!
Yep, you are right, 200 response and then fail.

Looking at #42, can't tell how it was worked out though :)
> <= [03/03 22:25:09] POST https://client-s.gateway.messenger.live.com/v1/users/ME/endpoints
{'json': {'endpointFeatures': 'Agent'}}
=> [03/03 22:25:10] 200
[{u'id': u'ce48cee1-22ba-158c-4e70-a08f915dc9e7',
  u'isActive': True,
  u'networks': [],
  u'policies': {},
  u'subscriptions': [{u'channelType': u'TcpSocket',
                      u'conversationType': 0,
                      u'eventChannel': u'',
                      u'eventServiceName': u'',
                      u'id': 0,
                      u'interestedResources': [u'/abch',
                                               u'/v1/threads/ALL',
                                               u'/v1/users/ME/conversations/ALL/messages',
                                               u'/v1/users/ME/conversations/ALL/properties',
                                               u'/v1/users/ME/contacts/ALL'],
                      u'packageSid': u'',
                      u'template': u'',
                      u'type': u'Subscription',
                      u'xuid': u''}],
  u'type': u'Endpoint'},
 {u'id': u'e06514b6-b0e3-bd1a-b0e3-42c442c4b0e3',
  u'isActive': False,
  u'networks': [],
  u'policies': {},
  u'subscriptions': [{u'channelType': u'TcpSocket',
                      u'conversationType': 0,
                      u'eventChannel': u'',
                      u'eventServiceName': u'',
                      u'id': 0,
                      u'interestedResources': [u'/v1/threads/ALL',
                                               u'/v1/users/ME/conversations/ALL/messages',
                                               u'/v1/users/ME/conversations/ALL/properties'],
                      u'packageSid': u'',
                      u'template': u'',
                      u'type': u'Subscription',
                      u'xuid': u''}],
  u'type': u'Endpoint'}]
<= [03/03 22:25:10] PUT https://client-s.gateway.messenger.live.com/v1/users/ME/endpoints/ce48cee1-22ba-158c-4e70-a08f915dc9e7/presenceDocs/messagingService
{'json': {'id': 'messagingService',
          'privateInfo': {'epname': 'skype'},
          'publicInfo': {'capabilities': '',
                         'nodeInfo': 'xx',
                         'skypeNameVersion': 'skype.com',
                         'type': 1,
                         'version': '908/1.30.0.128'},
          'selfLink': 'uri',
          'type': 'EndpointPresenceDoc'}}
=> [03/03 22:25:11] 404
{u'errorCode': 729,
 u'message': u'You must create an endpoint before performing this operation.'}

**Comment by OllieTerrance** [comment] 2017-03-03 23:41
Yep, the only endpoint there is a TcpSocket, presumably a desktop/mobile client?

It would help if I put the extra debug line in the right place...

```diff
diff --git a/skpy/conn.py b/skpy/conn.py
index de1fcdd..37e1d77 100644
--- a/skpy/conn.py
+++ b/skpy/conn.py
@@ -116,4 +116,5 @@ class SkypeConnection(SkypeObj):
         if os.getenv("SKPY_DEBUG_HTTP"):
             print("=> [{0}] {1}".format(datetime.now().strftime("%d/%m %H:%M:%S"), resp.status_code))
+            print(pformat(dict(resp.headers)))
             try:
                 print(pformat(resp.json()))
@@ -206,4 +207,5 @@ class SkypeConnection(SkypeObj):
         if os.getenv("SKPY_DEBUG_HTTP"):
             print("=> [{0}] {1}".format(datetime.now().strftime("%d/%m %H:%M:%S"), resp.status_code))
+            print(pformat(dict(resp.headers)))
             try:
                 print(pformat(resp.json()))
```

I've just pushed that to master, can you retry and paste the output again?  Should have headers this time.

**Comment by trikota** [comment] 2017-03-04 08:02
Something new!
This is what I got.
http://pastebin.com/nGWJKdn6

**Comment by OllieTerrance** [comment] 2017-03-04 09:50
Hrrm, now that looks like #44 (https://account.live.com/RecoverAccount in the output) -- what happens if you sign in with that account at https://web.skype.com?

**Comment by trikota** [comment] 2017-03-06 16:35
Hello again, sorry for my silence. Everything works now! 
Though I've done nothing in code and account. Signing in web.skype.com is ok now and was before.
Thanks for help! If you need more info I could try and get you some.

**Comment by OllieTerrance** [comment] 2017-03-06 18:03
Given the similar results here and in #42, it's looking like this is a temporary issue on the server side.  That said, I'm guessing Skype for Web has some handling for whatever this is, which is missing from SkPy.

I'll close this for now, but please report back if you get stuck again.  Best thing to do is to login from scratch (incognito or otherwise) to Skype for Web, with DevTools open to log the network requests, then we can compare with SkPy and see what's missing...

**Closed by OllieTerrance** 2017-03-06 18:03 UTC

**Comment by Imelstorm** [comment] 2017-05-03 08:50
I have the same problem reproduced in version 0.8

```
    self._skype = Skype(self.__username, self.__passwd, self.__token_path)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/skpy/main.py", line 69, in __init__
    self.conn.getSkypeToken()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/skpy/conn.py", line 264, in getSkypeToken
    self.liveLogin(user, pwd)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/skpy/conn.py", line 363, in liveLogin
    self.getRegToken()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/skpy/conn.py", line 423, in getRegToken
    endpoint.config()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/skpy/conn.py", line 866, in config
    "version": "908/1.30.0.128"}})
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/skpy/conn.py", line 217, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
skpy.core.SkypeApiException: ('404 response from PUT https://bn2-client-s.gateway.messenger.live.com/v1/users/ME/endpoints/{995483a1-a64b-4684-ad5c-ee121280ea34}/presenceDocs/messagingService', <Response [404]>)
```

**Comment by OllieTerrance** [comment] 2017-05-03 09:04
See previous comments:

> If you can reliably reproduce this, please compare the failing request with the corresponding one made by [Skype for Web](https://web.skype.com) in dev tools, it might be doing something differently to handle this case.

As this is something I've yet to reproduce on my account, I don't know what's missing unless you can find a difference between SkPy and Skype for Web.

**Comment by Imelstorm** [comment] 2017-05-03 14:45
I think this may be due to the fact that I run this code on two different machines, the one that got the token first, can continue to receive it normally, the other will receive this error

**Comment by OllieTerrance** [comment] 2017-05-03 16:37
Different regions?  That'll probably be the servers blocking you for possible abuse if you authenticate from multiple locations, though that normally gets caught earlier on...

**Comment by Imelstorm** [comment] 2017-05-03 17:34
Yes in different regions, when the instances are behind one gateway everything works fine, thanks for the help, I'll try to divide the regions into different accounts.
Maybe it's worth mentioning this in the documentation?
Thanks for the help again.

**Comment by Wafflespeanut** [comment] 2017-05-04 06:05
> Yes in different regions, when the instances are behind one gateway everything works fine

I second this. When I tried locally, it worked fine, but when I tried in my AWS machine (east region), it returned 404. Then, I tried in Google cloud (west region), and it worked fine.

**Comment by Wafflespeanut** [comment] 2017-05-04 08:01
And, one more thing. I wanted to say that this library is really cool! I just finished writing a bunch of wrapper scripts around it, and now I have an interactive bot in our company's Skype group. It's already turned out to be useful. So, thanks for doing this! 😄
